# Exercise Background

This small application based coding exercise is ment to expose you to the use of the numpy library as well as give you a taste of tasks that you might be needed to perform during machine learning. 

Usually, machine learning involves working on large data sets. This notebook will walk you through normalising the data and then dividing the data set into smaller subsets. It is recommended that while attempting each of the tasks visit the NumPy library to find the most appropriate function which can help you achieve the desired result. More often than not you will find the functions which you require prewritten in the library. The **numpy library** can be found [here.](https://numpy.org/doc/stable/) 

Without further ado, the first task is to mean normalise a data set. Mean normalising is a data transformation done to reduce the variations in the data set. For example, consider a data set which has integers between 0 and 10000. That is a lot of variation, and it becomes difficult to build ML algorithms on this data. So mean normalisation is done on such data, after the transformation, the mean of the data will be zero, and standard deviation will be 1.  Even though the actual values of data will change a lot, but the overall variation is still kept intact. If the concept of normalisation feels a bit unclear dont worry all of this will be covered in the future sections of this program. For now, let’s concentrate on the tasks at hand. 


# Task 1: Mean Normalisation: 

**Question 1.1** Create a 2D of random integers between 0 and 10,000 (including both 0 and 10,000) with 25000 rows and 15 columns. This will be the dataset you will use in the notebook. 

In [1]:
# import NumPy into Python
import numpy as np

# Create a 25000 x 15 ndarray with random integers in the interval [0, 10000].

n = np.random.randint(0,high = 10001,size = (25000,15))
# print the shape of X
n.shape

(25000, 15)

In [4]:
n

array([[3410, 7027, 9118, ..., 8799, 8546, 9975],
       [6679, 7981, 6624, ...,  798, 9620, 9966],
       [1857, 8088, 8144, ..., 2283, 4336, 9208],
       ...,
       [  92, 5700, 6088, ..., 7564, 1805, 7772],
       [6611, 4647, 6613, ...,  733, 4609,  995],
       [5782, 9006,  141, ..., 7251, 9051, 8398]])

In [3]:
# print the first row of X
n[0,:]


array([3410, 7027, 9118, 1376, 3341, 6438, 3120, 1657, 7638, 1953, 4140,
       3908, 8799, 8546, 9975])

Now that you created the array we will mean normalize it. The equation for normalisaing the data is given below:

$\mbox{Norm_Col}_i = \frac{\mbox{Col}_i - \mu_i}{\sigma_i}$

where $\mbox{Col}_i$ is the $i$th column of $X$, $\mu_i$ is average of the values in the $i$th column of $X$, and $\sigma_i$ is the standard deviation of the values in the $i$th column of $X$. To put it simply, to find the new value of each element, you have to subtract the mean of respective column form that value and divide the result with the standard deviation of that columns. Now the question is, Why are these operations being done column-wise? That is because usually all the procedures in ML are done column-wise. So it will be beneficial for us to develop the habit of thinking about data column-wise.   

**Question 1.2** Find the mean and the standard deviation of each of the columns in the dataset. The result will be two 1D arrays with 15 elements each, representing the mean and standard deviation for each of the columns in the dataset.  

In [5]:
# Average of the values in each column of X

c = np.average(n,axis = 0)
# print ave_cols  
print('ave_cols: \n',c, "\n")

# Standard Deviation of the values in each column of X
s = np.std(n,axis = 0)

# print std_cols  
print('\n std_cols:  \n',s,'\n')

ave_cols: 
 [4996.70624 5016.62044 5014.67196 4995.88568 5000.37012 5012.264
 4973.04644 5040.3608  5006.32572 5000.42728 5012.694   5014.2092
 5010.37248 5011.92092 5008.78504] 


 std_cols:  
 [2893.70483539 2881.30717507 2879.33887753 2891.86707004 2872.60449441
 2904.40088213 2902.8194326  2888.47369904 2880.7863798  2881.99246338
 2878.13349295 2892.95654948 2883.83944476 2879.32686734 2897.71461065] 



**Question 1.3** Print the shape of each both the arrays, they should have 15 elements each.  

In [6]:
# Print the shape of ave_cols
print(c.shape)
# Print the shape of std_cols
print(s.shape)

(15,)
(15,)


**Question 1.4** Now that you have mean and standard deviation calculated, it is time to apply the transformation to the dataset. 
 
**HINT** The broadcast property of NumPy can make this a lot easier. You can read about it [here](https://numpy.org/doc/stable/user/basics.broadcasting.html).
All you have to do is create one row of transformation values and repeat them through all the values.

In [7]:
# Mean normalize X
x = (n - c) / s
x

array([[-0.54833037,  0.69773177,  1.42509382, ...,  1.31374426,
         1.22739767,  1.71383853],
       [ 0.58136329,  1.02883149,  0.55892276, ..., -1.46068204,
         1.60040151,  1.71073264],
       [-1.08501261,  1.06596741,  1.08682172, ..., -0.94574352,
        -0.23474963,  1.44914718],
       ...,
       [-1.69495734,  0.23717692,  0.37276892, ...,  0.88549573,
        -1.11377453,  0.95358423],
       [ 0.557864  , -0.12828221,  0.55510244, ..., -1.48322144,
        -0.1399358 , -1.3851554 ],
       [ 0.27138005,  1.38457281, -1.69263576, ...,  0.77695987,
         1.40278588,  1.16961655]])

**Question 1.5** If the transformation has been performed correctly, the mean of elements in each column will be approximately 0. Also, the average of the **minimum** value in each column of X_norm and the average of the **maximum** value in each column of X_norm will have almost the same face value with opposite signs. Let’s confirm if the transformation has happened correctly. 

In [9]:
# Print the average of all the values of X_norm
print(np.average(x))

# Print the average of the minimum value in each column of X_norm
print(np.average(x.min(axis=0)))

# Print the average of the maximum value in each column of X_norm
print(np.average(x.max(axis=0)))

1.9137284349805365e-18
-1.7343542719731222
1.7290508622130512


Be mindful that the exact values might not match since the dataset was initialized using the random function. 

# Data Spliting 

After data processing, it is a regular practice in ML to split the dataset into three datasets. 

1. A Training Set
2. A Cross Validation Set
3. A Test Set

The ratios in which the data is split varies a bit from case to case. But the accepted standard 6:2:2 for train, test, and validation respectively. That is 60% for training data and so on. Again why is the data split or what is the signification of these smaller data sets? These questions are better left unanswered for now. 
The tanks assigned to you is to split the data in the given proportions randomly. 
For instance, if the data set had ten elements, this is how you would do it. 

In [11]:
# We create a random permutation of integers 0 to 9
np.random.permutation(10)

array([8, 3, 7, 5, 2, 6, 1, 9, 0, 4])

1. training set = 8,3,7,5,2,6
2. Cross Validation Set = 1,9
3. Test Set = 0,4

**Question 2.1** Similarly, create a 1D array representing the indexes of the rows in the dataset X_norm. U can use the   `np.random.permutation()` function for randomising the indexes. 

In [12]:
# Create a rank 1 ndarray that contains a random permutation of the row indices of `X_norm`


In [13]:
# Print the shape of row_indices


(25000,)

**Question 2.2** Split the row indexes in the needed proportions. You can use the slicing methods you have learnt in this session to make the job easier.  

In [17]:
# Make any necessary calculations.
# You can save your calculations into variables to use later.
train = row_indices[:15000]
test = row_indices[15000:20000]
val  = row_indices[20000:]

**Question 2.3** Now make use of the indexes that you made to split the data also similarly once the data is split print the shape of each of the smaller data sets. `X_train` should have 15000 rows and 15 columns. `X_test` should have 5000 rows and 15 columns. `X_val` should have 5000 rows and 15 columns. 

In [10]:
# Create a Training Set
ntrain = n[:15000,:]

# Create a Cross Validation Set
ntest = n[15000:20000,:]

# Create a Test Set
nval = n[20000:,:]

In [11]:
# Print the shape of X_train

print(ntrain.shape)
# Print the shape of X_crossVal
print(ntest.shape)

# Print the shape of X_test
print(nval.shape)

(15000, 15)
(5000, 15)
(5000, 15)
